apiVersion: v1
baseDomain: sandbox.acme.com
compute:
- name: worker
  hyperthreading: Enabled
  replicas: 0
  architecture: amd64
controlPlane:
  name: master
  replicas: 1
  architecture: amd64
  hyperthreading: Enabled
  platform:
    aws:
      type: m6a.2xlarge
      rootVolume:
        size: 150
        type: gp3
metadata:
  name: my-cluster
platform:
  aws:
    region: ap-southeast-1
    userTags:
      owner: "ateam@acme.com"
      team: "ateam"
      usage: "Dev"
      description: "Product Development and Demo environment for OpenShift"
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":...}}}'
sshKey: 'ssh-rsa ...'
